In [1]:
import numpy as np

In [2]:
arr = np.array(['가','나','다','라','마'])

# 배열의 두번째 값을 꺼내서 출력하세요.
arr[0:3]

array(['가', '나', '다'], dtype='<U1')

In [10]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# 배열의 처음 3개 값을 꺼내서 출력하세요.
print(arr[0:3])

[10 20 30]


In [11]:
# 배열의 네 번째부터 끝까지 값을 꺼내서 출력하세요.
print(arr[3:])

[40 50 60 70]


In [12]:
# 배열의 두 번째부터 다섯 번째까지 값을 꺼내서 출력하세요.
print(arr[1:5])

[20 30 40 50]


In [ ]:
arr = np.array(['a','b','c','d','e','f','g'])

In [13]:
# 배열의 처음 3개 값을 꺼내서 출력하세요.
print(arr[:3])

[10 20 30]


In [ ]:
array([1,2,3])

In [ ]:
# 1 꺼내기


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

In [18]:
print(arr[arr > 30])

[40 50 60 70]


In [19]:
print(arr[arr % 2 == 0])

[10 20 30 40 50 60 70]


In [26]:
arr[arr > 50] = 999

In [27]:
print(arr)

[ 10  20  30  40  50 999 999]


In [4]:
employees = np.array(['짱구','철수','유리','맹구','훈이'])

salaries = np.array([250,320,280,400,150])

In [16]:
employees == '맹구'

array([False,  True])

In [17]:
salaries >= 300

array([False,  True, False,  True, False])

In [20]:
# employees[salaries >= 300] => 오류남 

In [29]:
arr = np.array([5,12,7,20,3])

result = np.where(arr > 10, 100, 0)
result

array([  0, 100,   0, 100,   0])

In [31]:
arr = np.array([15,8,22,6,13])

result = np.where(arr %2 == 0, 1, -1)
result

array([-1,  1,  1,  1, -1])

In [32]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([1, 2, 3, 4, 5])
cond = np.array([True, False, True, False, True])

np.where(cond, arr1, arr2)

array([10,  2, 30,  4, 50])

In [40]:
# 아래는 하루 동안 먹은 음식들의 칼로리(Kcal)이다.
# • 김밥: 250
# • 라면: 550
# • 떡볶이: 400
# • 치킨: 800
calories = np.array([250, 550, 400, 800])

# 1. 총 칼로리 합계
total_calories = np.sum(calories)

# 2. 평균 칼로리
average_calories = np.mean(calories)

# 3. 가장 높은 칼로리
max_calories = np.max(calories)

# 4. 가장 낮은 칼로리
min_calories = np.min(calories)

print(f"총 칼로리: {total_calories}")
print(f"평균 칼로리: {average_calories}")
print(f"가장 높은 칼로리: {max_calories}")
print(f"가장 낮은 칼로리: {min_calories}")

총 칼로리: 2000
평균 칼로리: 500.0
가장 높은 칼로리: 800
가장 낮은 칼로리: 250
